version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: laravel-mysql
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'laravel'
       MYSQL_USER: 'laravel'
       MYSQL_PASSWORD: 'laravel'
       TZ: "Asia/Jakarta"
     restart: unless-stopped

   php:
     depends_on:
       - db
     build: .
     container_name: laravel-php
     ports:
       - "80:80"
     environment:
       TZ: "Asia/Jakarta"
     restart: unless-stopped

volumes:
    db_data: {}